{
    "openapi": "3.0.0",
    "info": {
      "title": "API Pokemon",
      "description": "Documentation of API Pokemon",
      "contact": {
        "name": "MaestroShifu",
        "url": "https://github.com/MaestroShifu",
        "email": "sdanielsarsantos@gmail.com"
      },
      "version": "1.0.0"
    },
    "servers": [
      {
        "url": "http://localhost:3000/api/v1",
        "description": "Development server"
      },
      {
        "url": "http://production:3000/api/v1",
        "description": "Production server... coming soon"
      }
    ],
    "tags": [
      {
        "name": "ManageAuth",
        "description": "Manejo de autenticacion en el sistema"
      },
      {
        "name": "ManagePokemon",
        "description": "Operaciones basicas con los pokemones"
      }
    ],
    "security": [],
    "paths": {
      "/auth/register": {
        "summary": "Manejo de creacion de usuarios",
        "description": "Sirve para agregar nuevos usuarios en la plataforma",
        "post": {
          "tags": [
            "ManageAuth"
          ],
          "summary": "Crear usuario",
          "description": "Sirve para registrar un nuevo usuario en la plataforma",
          "operationId": "registerAuth",
          "requestBody": {
            "$ref": "#/components/requestBodies/auth_register"
          },
          "responses": {
            "201": {
              "$ref": "#/components/responses/auth_response"
            },
            "400": {
              "$ref": "#/components/responses/general_error_response"
            },
            "500": {
              "$ref": "#/components/responses/general_error_response"
            }
          }
        }
      },
      "/auth/login": {
        "summary": "Manejo de autenticacion de usuarios",
        "description": "Sirve para la autenticacion en nuestra api",
        "post": {
          "tags": [
            "ManageAuth"
          ],
          "summary": "Ingresar con un usuario",
          "description": "Sirve para ingresar en nuestra plataforma",
          "operationId": "loginAuth",
          "requestBody": {
            "$ref": "#/components/requestBodies/auth_login"
          },
          "responses": {
            "201": {
              "$ref": "#/components/responses/auth_response"
            },
            "400": {
              "$ref": "#/components/responses/general_error_response"
            },
            "500": {
              "$ref": "#/components/responses/general_error_response"
            }
          }
        }
      },
      "/me/pokemon": {
        "summary": "Listar los pokemones del usuario",
        "description": "Listar todos los pokemones del usuario",
        "get": {
          "tags": [
            "ManagePokemon"
          ],
          "summary": "Listar todos los pokemones del usuario",
          "description": "Listar todos los pokemones del usuario",
          "operationId": "meGetPokemon",
          "responses": {
            "200": {
              "$ref": "#/components/responses/pokemon_array_response"
            },
            "400": {
              "$ref": "#/components/responses/general_error_response"
            },
            "401": {
              "$ref": "#/components/responses/general_error_response"
            },
            "500": {
              "$ref": "#/components/responses/general_error_response"
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/components/parameters/x-access-token"
          }
        ]
      },
      "/pokemon": {
        "summary": "Manejo de de los pokemones de la plataforma",
        "description": "Sirve para el manejo de los pokemones",
        "get": {
          "tags": [
            "ManagePokemon"
          ],
          "summary": "Listar todos los pokemones",
          "description": "Lista todos los pokemones publicos de la plataforma",
          "operationId": "getPokemon",
          "responses": {
            "200": {
              "$ref": "#/components/responses/pokemon_array_response"
            },
            "400": {
              "$ref": "#/components/responses/general_error_response"
            },
            "401": {
              "$ref": "#/components/responses/general_error_response"
            },
            "500": {
              "$ref": "#/components/responses/general_error_response"
            }
          }
        },
        "post": {
          "tags": [
            "ManagePokemon"
          ],
          "summary": "Creaciones de pokemones",
          "description": "Sirve para ingresar un nuevo pokemon a la plataforma",
          "operationId": "postPokemon",
          "requestBody": {
            "$ref": "#/components/requestBodies/create_pokemon"
          },
          "responses": {
            "201": {
              "$ref": "#/components/responses/pokemon_response"
            },
            "400": {
              "$ref": "#/components/responses/general_error_response"
            },
            "401": {
              "$ref": "#/components/responses/general_error_response"
            },
            "500": {
              "$ref": "#/components/responses/general_error_response"
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/components/parameters/x-access-token"
          }
        ]
      },
      "/pokemon/{id}": {
        "summary": "Manejo de de los pokemones de la plataforma",
        "description": "Sirve para el manejo de los pokemones",
        "get": {
          "tags": [
            "ManagePokemon"
          ],
          "summary": "Consultar un pokemon especifico",
          "description": "Consultar un pokemon por id",
          "operationId": "getByIdPokemon",
          "responses": {
            "200": {
              "$ref": "#/components/responses/pokemon_response"
            },
            "400": {
              "$ref": "#/components/responses/general_error_response"
            },
            "401": {
              "$ref": "#/components/responses/general_error_response"
            },
            "500": {
              "$ref": "#/components/responses/general_error_response"
            }
          }
        },
        "put": {
          "tags": [
            "ManagePokemon"
          ],
          "summary": "Actualizar los pokemones que posee el usuario",
          "description": "Sirve para actualizar un pokemon",
          "operationId": "putPokemon",
          "requestBody": {
            "$ref": "#/components/requestBodies/update_pokemon"
          },
          "responses": {
            "200": {
              "$ref": "#/components/responses/pokemon_response"
            },
            "400": {
              "$ref": "#/components/responses/general_error_response"
            },
            "401": {
              "$ref": "#/components/responses/general_error_response"
            },
            "500": {
              "$ref": "#/components/responses/general_error_response"
            }
          }
        },
        "delete": {
          "tags": [
            "ManagePokemon"
          ],
          "summary": "Eliminar pokemones",
          "description": "Eliminar pokemones especificos de la plataforma",
          "operationId": "deletePokemon",
          "responses": {
            "204": {
              "description": "Manejo exitoso de eliminacion de un pokemon"
            },
            "400": {
              "$ref": "#/components/responses/general_error_response"
            },
            "401": {
              "$ref": "#/components/responses/general_error_response"
            },
            "500": {
              "$ref": "#/components/responses/general_error_response"
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/components/parameters/x-access-token"
          },
          {
            "$ref": "#/components/parameters/id-path"
          }
        ]
      },
      "/pokemon/deleteall": {
        "summary": "Eliminar todos los pokemon",
        "description": "Sirve para eliminar todos los pokemons que poseo",
        "delete": {
          "tags": [
            "ManagePokemon"
          ],
          "summary": "Eliminar pokemones",
          "description": "Eliminar todos mis pokemones",
          "operationId": "deleteAllPokemon",
          "responses": {
            "204": {
              "description": "Manejo exitoso de eliminacion de un pokemon"
            },
            "400": {
              "$ref": "#/components/responses/general_error_response"
            },
            "401": {
              "$ref": "#/components/responses/general_error_response"
            },
            "500": {
              "$ref": "#/components/responses/general_error_response"
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/components/parameters/x-access-token"
          }
        ]
      }
    },
    "components": {
      "parameters": {
        "x-access-token": {
          "name": "x-access-token",
          "in": "header",
          "description": "Token de acceso",
          "required": true,
          "schema": {
            "type": "string"
          }
        },
        "id-path": {
          "name": "id",
          "in": "path",
          "description": "Id que se desea consultar",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      },
      "schemas": {
        "auth_register_body": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "maxLength": 300
            },
            "name": {
              "type": "string",
              "maxLength": 300,
              "minLength": 2
            },
            "last_name": {
              "type": "string",
              "maxLength": 300,
              "minLength": 2
            },
            "password": {
              "type": "string",
              "minLength": 10
            },
            "re_password": {
              "type": "string",
              "minLength": 10
            }
          },
          "required": [
            "email",
            "password",
            "re_password"
          ],
          "additionalProperties": false
        },
        "auth_login_body": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "maxLength": 300
            },
            "password": {
              "type": "string",
              "minLength": 10
            }
          },
          "required": [
            "email",
            "password"
          ],
          "additionalProperties": false
        },
        "auth_response": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "maxLength": 300
            },
            "name": {
              "type": "string",
              "maxLength": 300,
              "minLength": 2
            },
            "last_name": {
              "type": "string",
              "maxLength": 300,
              "minLength": 2
            },
            "token": {
              "type": "string",
              "maxLength": 500
            }
          },
          "required": [
            "email",
            "token"
          ],
          "additionalProperties": false
        },
        "general_error": {
          "type": "object",
          "properties": {
            "statusCode": {
              "type": "string",
              "enum": [
                "400",
                "500"
              ]
            },
            "message": {
              "type": "string",
              "maxLength": 300
            }
          },
          "required": [
            "statusCode",
            "message"
          ],
          "additionalProperties": false
        },
        "types_pokemon": {
          "type": "string",
          "enum": [
            "Acero",
            "Agua",
            "Bicho",
            "Dragon",
            "Electrico",
            "Fantasma",
            "Fuego",
            "Hada",
            "Hielo",
            "Lucha",
            "Normal",
            "Planta",
            "Psiquico",
            "Roca",
            "Siniestro",
            "Tierra",
            "Veneno",
            "Volador",
            "???"
          ]
        },
        "crear_pokemon_body": {
          "type": "object",
          "properties": {
            "types": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/types_pokemon"
              }
             },
             "name": {
               "type": "string",
               "maxLength": 300
             },
             "ability": {
              "type": "string",
              "maxLength": 300
            },
            "is_public": {
              "type": "boolean"
            },
            "url_image": {
              "type": "string",
              "maxLength": 500
            }
          },
          "required": [
            "ability",
            "name",
            "types"
          ],
          "additionalProperties": false
        },
        "types_body":{
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "name": {
              "type": "string",
              "enum": [
                "Acero",
                "Agua",
                "Bicho",
                "Dragon",
                "Electrico",
                "Fantasma",
                "Fuego",
                "Hada",
                "Hielo",
                "Lucha",
                "Normal",
                "Planta",
                "Psiquico",
                "Roca",
                "Siniestro",
                "Tierra",
                "Veneno",
                "Volador",
                "???"
              ]
            }
          },
          "required": [
            "id",
            "name"
          ],
          "additionalProperties": false
        },
        "pokemon_body": {
          "type": "object",
          "properties": {
            "types": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/types_body"
              }
             },
             "name": {
               "type": "string",
               "maxLength": 300
             },
             "ability": {
              "type": "string",
              "maxLength": 300
            },
            "is_public": {
              "type": "boolean"
            },
            "url_image": {
              "type": "string",
              "maxLength": 500
            },
            "profile_id": {
              "type": "integer"
            },
            "id": {
              "type": "integer"
            }
          },
          "required": [
            "ability",
            "name",
            "types",
            "is_public",
            "url_image",
            "profile_id",
            "id"
          ],
          "additionalProperties": false
        },
        "pokemon_array_body": {
          "type": "array",
          "items": {
            "$ref": "#/components/schemas/pokemon_body"
          }
        },
        "update_pokemon_body": {
          "type": "object",
          "properties": {
            "add_types": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/types_pokemon"
              }
            },
            "remove_types": {
              "type": "array",
              "items": {
                "$ref": "#/components/schemas/types_pokemon"
              }
            },
            "name": {
              "type": "string",
              "maxLength": 300
            },
            "ability": {
              "type": "string",
              "maxLength": 300
            },
            "is_public": {
              "type": "boolean"
            },
            "url_image": {
              "type": "string",
              "maxLength": 500
            }
          },
          "additionalProperties": false
        }
      },
      "examples": {
        "auth_register_body_example": {
          "summary": "Registro de nuevos usuarios",
          "value": {
            "email": "sdanielsarsantos@gmail.com",
            "password": "daniSlsas]",
            "re_password": "daniSlsas]"
          }
        },
        "auth_login_body_example": {
          "summary": "Ingreso de un usuario",
          "value": {
            "email": "sdanielsarsantos@gmail.com",
            "password": "daniSlsas]"
          }
        },
        "auth_response_example": {
          "summary": "Respuesta al autenticar en la api",
          "value": {
            "email": "sdanielsarsantos@gmail.com",
            "name": "daniel",
            "last_name": "santos",
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsImVtYWlsIjoic2RhbmllbHNhcnNhbnRvc0BnbWFpbC5jb20iLCJpYXQiOjE2Mjg5OTQyNTIsImV4cCI6MTYyOTAwMTQ1Mn0.2HopQy5sD2YJgUjh9RPsdE7B8YEO6YG7AgZuDgP9uFM"
          }
        },
        "general_error_example": {
          "summary": "Manejo de error del api",
          "value": {
            "statusCode": "500",
            "message": "Error del lado del servidor :3"
          }
        },
        "crear_pokemon_example": {
          "summary": "Ejemplo crear un nuevo pokemon",
          "value": {
            "name": "pikachu",
            "ability": "Electricidad estática",
            "types": ["Eléctrico"]
          }
        },
        "crear_pokemon_body_example": {
          "summary": "Cuerpo de un pokemon",
          "value": {
            "name": "pikachu",
            "ability": "Electricidad estática",
            "is_public": false,
            "url_image": "https://static.wikia.nocookie.net/espokemon/images/7/77/Pikachu.png/revision/latest?cb=20150621181250",
            "profile_id": 1,
            "id": 9,
            "types": [
              {
                "id": 5,
                "name": "Eléctrico"
              },
              {
                "id": 18,
                "name": "Volador"
              }
            ]
          }
        },
        "update_pokemon_example": {
          "summary": "Ejemplo para actualizar un pokemon",
          "value": {
            "name": "pikachu",
            "ability": "Electricidad estática",
            "is_public": false,
            "url_image": "https://static.wikia.nocookie.net/espokemon/images/7/77/Pikachu.png/revision/latest?cb=20150621181250",
            "add_types": ["Volador"],
            "remove_types": ["Eléctrico"]
          }
        }
      },
      "responses": {
        "auth_response": {
          "description": "Es la respuesta de un proceso de autenticacion",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/auth_response"
              },
              "examples": {
                "auth_response_example": {
                  "$ref": "#/components/examples/auth_response_example"
                }
              }
            }
          }
        },
        "general_error_response": {
          "description": "La repuesta general en caso de error del api",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/general_error"
              },
              "examples": {
                "auth_response_example": {
                  "$ref": "#/components/examples/general_error_example"
                }
              }
            }
          }
        },
        "pokemon_response": {
          "description": "Es la respuesta de un pokemon",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/pokemon_body"
              },
              "examples": {
                "crear_pokemon_body_example": {
                  "$ref": "#/components/examples/crear_pokemon_body_example"
                }
              }
            }
          }
        },
        "pokemon_array_response": {
          "description": "Es una lista de pokemones",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/pokemon_array_body"
              },
              "examples": {
                "crear_pokemon_body_example": {
                  "$ref": "#/components/examples/crear_pokemon_body_example"
                }
              }
            }
          }
        }
      },
      "requestBodies": {
        "auth_register": {
          "description": "Body para crear un usuario nuevo",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/auth_register_body"
              },
              "examples": {
                "auth_register_body_example": {
                  "$ref": "#/components/examples/auth_register_body_example"
                }
              }
            }
          }
        },
        "auth_login": {
          "description": "Body para ingresar con un usuario",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/auth_login_body"
              },
              "examples": {
                "auth_login_body_example": {
                  "$ref": "#/components/examples/auth_login_body_example"
                }
              }
            }
          }
        },
        "create_pokemon": {
          "description": "Body para crear nuevos pokemones",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/crear_pokemon_body"
              },
              "examples": {
                "crear_pokemon_example": {
                  "$ref": "#/components/examples/crear_pokemon_example"
                }
              }
            }
          }
        },
        "update_pokemon": {
          "description": "Body para actualizar a los pokemones",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/update_pokemon_body"
              },
              "examples": {
                "update_pokemon_example": {
                  "$ref": "#/components/examples/update_pokemon_example"
                }
              }
            }
          }
        }
      }
    }
  }